### ISSUE TITLE
Placeholder  font size bug

### ISSUE THREAD

**Issue by VinnichenkoD** [oleghnidets/TweeTextField#5] opened 2018-02-08 15:32 UTC
Hello.
I have a problem with the display of the empty field's placeholder. In two different situations, the size of the text of the placeholder is different.

Example:
There are two fields of type TweeAttributedTextField.
1) If I have the field # 1 selected and I manually tap on the field # 2 - the Placeholder font # 1 has the correct dimensions
2) If I have the field # 1 selected and I go to the next field using the becomeFirstResponder method, the # 1 Placeholder font is larger than the specified

The difference is not significant, but noticeable

In the above examples, the fields are always empty

TweeTextField version (1.0.4)
Xcode Version 9.2
Swift 4
iOS 11.2.1

**Comment by oleghnidets** [comment] 2018-02-08 16:24
Hi,
I will investigate & fix asap.

**Comment by oleghnidets** [comment] 2018-02-09 11:08
Hi,
Take a look at https://github.com/oleghnidets/TweeTextField/releases/tag/1.0.5 
Let me know whether it works for you.

**Comment by VinnichenkoD** [comment] 2018-02-10 14:24
Hi
Now, in the end, the field has the correct size, only the animation shows that it passes through an enlarged font.

Сheck this
https://www.dropbox.com/s/ittp39jdrzyyqy9/ScreenRecording_02-10-2018%2016-16-12.MP4?dl=0

**Comment by oleghnidets** [comment] 2018-02-10 15:19
Thanks for response.
I see.. :( Probably, it is because the animation is fast. 
I will be investigating this.

**Comment by yarodevuci** [comment] 2018-02-13 05:26
@oleghnidets @VinnichenkoD both of you guys are speak Russian why talk English :D. Действительно чего эт я

**Comment by oleghnidets** [comment] 2018-02-13 13:21
Hi @VinnichenkoD @yarodevuci 
I believe I have fixed. I tried to reproduce and now I can't. 
Please, update pod. If you will face the issue again let me know. 

@yarodevuci Because not all users would understand us 😉

**Comment by VinnichenkoD** [comment] 2018-02-13 13:52
Hello @oleghnidets 
Apparently the problem was solved. Looks pretty good.
Thanks for the supporting 👍

**Closed as completed** 2018-02-13 13:58 UTC
Labels: bug
